### ISSUE TITLE
MacOS setup instructions

### ISSUE THREAD

**Issue by NiklasAurora** [dbwebb-se/inspect-gui#1]
```
brew install dialog coreutils
```

will install the necessary modules for the program to run.

**Comment by NiklasAurora** [comment]
Installation:
```
dbwebb init databas
cd databas
git clone git@github.com:dbwebb-se/inspect-gui.git
brew install dialog coreutils
make install 
```
and you might need to copy `inspect/gui_config.bash` to `~/.dbwebb/gui_config.bash` and update it to your liking (`DBWEBB_TEACHER_SIGNATURE` and `DBWEBB_BROWSER`)

Usage (make sure that Docker is running):
```
inspect-gui/gui.bash
```
use the first alternative and enter the acronym on the student you wish to inspect.

Tips:
Use tmux or two terminal windows next to each other, one viewing the GUI and one keeping a track on the inspect log. `tail -f .log/inspect/gui-inspect.ansi`

Problems:
Docker might complain about the following error:
> 2 matches found based on name: network databas_default is ambiguous

The easiest fix is to remove one of the two networks created, `docker network ls` to view created networks and `docker network rm <network_id>` to remove it.

**Comment by mosbth** [comment]
Do you remember what program we missed? `realpath` right?

**Comment by mosbth** [comment]
The README is written to exaplin how to get going and the script will check if `realpath` and 'dialog` exits upon startup.
