### ISSUE TITLE
gui_config.bash not easily accessible

### ISSUE THREAD

**Issue by NiklasAurora** [dbwebb-se/inspect-gui#2]
With a new installation (`dbwebb gui install`), you don't have an easy way to get the config file, since the installation is done as a binary. Currently, the only way to get the config is to download it from the repo itself.

**Comment by mosbth** [comment]
One can (v2.2.1) install a new configuration file, downloaded from this repo, by using the admin menu, or executing `gui.bash config`.

The integration is also improved so that this can be done through `dbwebb gui config` (v2.6.1 of dbwebb-cli).
